export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFRESH: "POPULAR_REFRESH", // 列表下来刷新时触发，加载最热模块的数据
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL", // 数据加载失败
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', // 加载更多数据成功
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL'
}
