export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFRESH: "POPULAR_REFRESH", // 列表下来刷新时触发，加载最热模块的数据
    LOAD_POPULAR_FAIL: "LOAD_POPULAR_FAIL", // 数据加载失败
    LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS",
}
