export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",

    POPULAR_REFRESH: "POPULAR_REFRESH", // 列表下来刷新时触发，加载最热模块的数据
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL", // 数据加载失败
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS', // 加载更多数据成功
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',

    TRENDING_REFRESH: "TRENDING_REFRESH", // 列表下来刷新时触发，加载最热模块的数据
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL", // 数据加载失败
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS', // 加载更多数据成功
    TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',

    FAVORITE_LOAD_DATA: "FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS: "FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL: "FAVORITE_LOAD_FAIL"
}
